### ISSUE TITLE
How to use `setup`?

### ISSUE THREAD

**Issue by alexgleason** [Byzanteam/kysely_postgres_js_dialect#10]
Hi, the documentation is a little unclear. I need to get a Kysely object, and I don't understand from the readme how I'm supposed to do that. Why do I need to define a top-level callback function?

**Comment by fahchen** [comment]
We've updated the documentation. Please review it at [Kysely Deno Postgres Dialect](https://github.com/Byzanteam/kysely_postgres_js_dialect?tab=readme-ov-file#use-kysely-deno-postgres-dialect). Feel free to comment if you have any further questions.
